'use strict';
ionicApp
.constant('LANGUAGE', {
    'en':{
        'importWallet': 'Import Wallet',
        'createWallet': 'Create Wallet',
        'save': 'Save',
        'ok': 'OK',
        'cancel': 'Cancel',
        'fund':'Fund',
        'members':'Members',
        'sr':'Fee ¥ ',
        'join':'Join Now',
        'renewals':'Renewals',
        'balance':'Balance',
        'nationality':'Nationality',
        'id':'ID Number',
        'flight':'My Flights',
        'wallet':'My Ether Wallet',
        'productDetailTitle':'Flight Accident Mutual Aid Plan',
        'productDetailText':'Protection of age 0-90 | Flight accident comprehensive protection',
        'name':'Name',
        'defaultPlaceholder':'Please enter',
        'provision':'Terms and Privacy',
        'tip1':'I agree to the flight accident mutual aid plan',
        'tip2':'',
        'tip3':'Approximately',
        'tip4':'Click the \'Create Wallet\' button below to create a new wallet, or select the \'Import Wallet\' tab to use an existing wallet.',
        'tip5':'Your wallet has been generated',
        'tip6':'Please save and backup. Do not forget your private key and password. If you do not save, there is no way to recover the wallet.',
        'tip7':'Flight Accident Mutual Aid Plan',
        'tip8':'Flight Accident Mutual Aid Plan pays you, or your beneficiary a lump sum benefit (e.g., 10000 ETH) when an accident results in your death or the loss of a limb or the loss of your eyesight.',
        'tip9':'Protection of age 0-90, flight accident comprehensive protection',
        'tip10':'Please input the password to unlock the wallet.',
        'refresh':'Refresh',
        'close':'Close',
        'walletAddress':'Address',
        'walletBalance':'Balance',
        'walletPasswordPlaceholder':'Enter your password to view wallet information',
        'passwordPlaceholder':'Enter your password (at least 9 characters)',
        'rechargePlaceholder':'ETH amount',
        'decrypt':'Unlock My Wallet',
        'nowPrice':'Current Price',
        'rechargeRecord':'Recent Activities',
        'address':'Address',
        'orderNo':'Order Number',
        'orderStatus':'Order Status',
        'createDate':'Create Time',
        'amount':'Amount',
        'previous':'Previous',
        'next':'Next',
        'recharge':'Deposit',
        'createWallet':'Create Wallet',
        'bindWallet':'Bind wallet',
        'privatekey':'PrivateKey',
        'unencrypted':'Unencrypted',
        'addFlight':'Add Flight',
        'pullDownToRefresh':'Pull to Refresh',
        'flightNumber':'Flight',
        'departureTime':'Departure',
        'arrivesTime':'Arrive',
        'applicationClaims':'Claim',
        'no':'No',
        'applicationStatus':'Application Status',
        'menuHome':'Plans',
        'menuMe':'Me',
        'menuFlight':'Flights',
        'menuProgram':'Notices',
        'claimStatus1':'Claim Filed',
        'claimStatus2':'Claim Succeeded',
        'claimStatus3':'Claim Denied',
        'claimStatus4':'In Review',
        'orderStatus1':'Initialization',
        'orderStatus2':'Paid',
        'orderStatus3':'Sending',
        'orderStatus4':'The transaction was successful',
        'orderStatus5':'Transaction failed',
        'errMsg1':'Please enter flight number and departure time',
        'errMsg2':'Takeoff time is incorrect',
        'errMsg3':'Registration failed',
        'errMsg4':'Application failed',
        'errMsg5':'No claim qualification',
        'errMsg6':'Failed to get user information',
        'errMsg7':'Get ETH and RMB exchange rate failure',
        'errMsg8':'Failed to get the information',
        'errMsg9':'Not added',
        'errMsg10':'Insufficient balance',
        'errMsg11':'Payment failed',
        'errMsg12':'Please fill in the name',
        'errMsg13':'Please fill in your nationality',
        'errMsg14':'Please fill in the ID number',
        'errMsg15':'Request failed',
        'errMsg16':'Account balance is too low',
        'errMsg17':'Account balance is too low',
        'errMsg18':'Wrong Password',
        'tipMsg1':'Transaction sent.',
        'tipMsg2':'The registration is successful',
        'tipMsg3':'Successful application',
        'tipMsg4':'login successful',
        'tipMsg5':'Joined',
        'tipMsg6':'Payment successful',
        'tipMsg7':'Renewal success',
        'tipMsg8':'Join success',
        'tipMsg9':'Please enter a password with a minimum of 9 digits'
    },
    'ch':{
        'importWallet': '导入钱包',
        'createWallet': '创建钱包',
        'ok': '确定',
        'save': '保存',
        'cancel': '取消',
        'fund':'总金额',
        'members':'参与人数',
        'sr':'会费',
        'join':'立即加入',
        'renewals':'续费',
        'balance':'计划内余额',
        'nationality':'国籍',
        'id':'身份证',
        'flight':'我的航班',
        'wallet':'我的以太钱包',
        'productDetailTitle':'航空意外互助计划',
        'productDetailText':'保障年龄0-90周岁 ｜ 突发意外全面保障',
        'name':'姓名',
        'defaultPlaceholder':'请输入',
        'provision':'保障计划',
        'tip1':'本人已充分了解本互助计划，并承诺填写信息的真实性，理解并同意',
        'tip2':'的全部内容',
        'tip3':'约为',
        'tip4':'账号还未绑定钱包，请先生成并绑定钱包',
        'tip5':'你的钱包已经生成',
        'tip6':'请做好保存和备份。不要忘记你的私钥和密码。如果你没有保存，没有办法恢复钱包。',
        'tip7':'航空意外最高可获100万元保障',
        'tip8':'亚洲欧洲澳洲美洲非洲中东通保',
        'tip9':'保障年龄0-90周岁，突发意外全面保障',
        'tip10':'请先解锁钱包',
        'refresh':'刷新',
        'close':'关闭',
        'walletAddress':'钱包地址',
        'walletBalance':'钱包余额',
        'walletPasswordPlaceholder':'输入密码查看钱包信息',
        'passwordPlaceholder':'输入一个强密码（至少9位）',
        'rechargePlaceholder':'ETH个数',
        'decrypt':'解锁',
        'nowPrice':'当前价格',
        'rechargeRecord':'充值记录',
        'address':'地址',
        'orderNo':'订单号',
        'orderStatus':'订单状态',
        'createDate':'创建时间',
        'amount':'金额',
        'previous':'上一页',
        'next':'下一页',
        'recharge':'充值',
        'createWallet':'生成钱包',
        'bindWallet':'绑定钱包',
        'privatekey':'私钥',
        'unencrypted':'未加密',
        'addFlight':'登记',
        'pullDownToRefresh':'下拉刷新',
        'flightNumber':'航班号',
        'departureTime':'起飞时间',
        'arrivesTime':'到达时间',
        'applicationClaims':'申请理赔',
        'no':'编号',
        'applicationStatus':'申请状态',
        'menuHome':'计划介绍',
        'menuMe':'个人主页',
        'menuFlight':'我的航班',
        'menuProgram':'理赔公示',
        'claimStatus1':'理赔初始化',
        'claimStatus2':'理赔审核成功',
        'claimStatus3':'理赔审核失败',
        'claimStatus4':'理赔审核中',
        'orderStatus1':'初始化',
        'orderStatus2':'已支付',
        'orderStatus3':'发送中',
        'orderStatus4':'交易成功',
        'orderStatus5':'交易失败',
        'errMsg1':'请输入航班号和起飞时间',
        'errMsg2':'起飞时间不正确',
        'errMsg3':'登记失败',
        'errMsg4':'申请失败',
        'errMsg5':'没有理赔资格',
        'errMsg6':'获取用户信息失败',
        'errMsg7':'获取ETH和RMB汇率失败',
        'errMsg8':'获取信息失败',
        'errMsg9':'未加入',
        'errMsg10':'余额不足，请续费',
        'errMsg11':'支付失败',
        'errMsg12':'请填写姓名',
        'errMsg13':'请填写国籍',
        'errMsg14':'请填写身份证号',
        'errMsg15':'请求失败',
        'errMsg16':'钱包不存在或余额不足',
        'errMsg17':'余额不足请续费',
        'errMsg18':'密码错误',
        'tipMsg1':'正在处理，可能需要几分钟请稍等',
        'tipMsg2':'登记成功',
        'tipMsg3':'申请成功',
        'tipMsg4':'登录成功',
        'tipMsg5':'已加入',
        'tipMsg6':'支付成功',
        'tipMsg7':'续费成功',
        'tipMsg8':'加入成功',
        'tipMsg9':'请输入长度至少为9位的密码'
    }
})
;
